const core = require('@angular/core');
// DO NOT EDIT THIS FILE, EDIT THE WEBPACK COMMON CONFIG INSTEAD, WHICH WILL MODIFY THIS FILE
let _VERSION = '0.0.0'; // This value will be overwritten by webpack
let _DEBUG_INFO_ENABLED = true; // This value will be overwritten by webpack
let _API_URL = '';
let _WS_SECURE = false;
let _WS_HOST = '';
let _WS_PORT = 0;
/* @toreplace VERSION */
/* @toreplace DEBUG_INFO_ENABLED */
/* @toreplace API_URL */
/* @toreplace WS_SECURE */
/* @toreplace WS_HOST */
/* @toreplace WS_PORT */
export const VERSION = _VERSION;
export const DEBUG_INFO_ENABLED = _DEBUG_INFO_ENABLED;
export const API_URL = _API_URL;
export const WS_SECURE = _WS_SECURE;
export const WS_HOST = _WS_HOST;
export const WS_PORT = _WS_PORT;
